options(repos = c(CRAN = "https://cran.uk.r-project.org/"))
# Install and load necessary R packages
install.packages("ggplot2")
install.packages("lubridate") #to use pythong 
install.packages("reticulate")
install.packages("gridExtra")

library(ggplot2)
library(lubridate)
library(reticulate)
library(gridExtra)


# path to csv log file generated by the Python script
log_file <- "watering_system/Automatic-Plant-Watering-System/starting_system/mositure_log.csv" # from start_watering_system.py script

# function to read and plot data
plot_data <- function() {
	# check if log file exists
	if (!file.exists(log_file)) {
		cat("Waiting for the log file to be created...\n")
		Sys.sleep(1)
		return()
	}
	
	# read the log data
	log_data <- read.csv(log_file, stringsAsFactors = FALSE)
	
	# log data
	log_data$Timestamp <- as.POSIXct(log_data$Timestamp, format = "%Y-%m-%d %H:%M:%S")
	# convert pump status to binary for plotting
	log_data$PumpStatusBinary <- ifelse(log_data$PumpStatus == "ON", 1, 0)
	
	# plot humidity levels over time
	humidity_plot <- ggplot(log_data, aes(x= Timestamp, y= Humidity)) +
	geom_line(color = "blue") +
	labs(title = "Humidity Levels Over Time", x = "Time", y = "Humidity (%)") +
	theme_minimal()

	# plot pump status over time
	pump_status_plot <- ggplot(log_data, aes(x= Timestamp, y= PumpStatusBinary)) +
	geom_line(color = "red") +
	labs(title = "Pump Status Over Time",x = "Time",y = "Pump Status (ON = 1, OFF = 0") +
	theme_minimal()

	# combine plots
	grid.arrange(humidity_plot, pump_status_plot, ncol = 1)
}


# continuously update the plots in real-time
while (TRUE) {
	plot_data()
	Sys.sleep(10) # update interval in seconds = 10 seconds ** change this after testing the script
}
